/**
 * Authentication
 */
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGIN_AS_GUEST = 'LOGIN_AS_GUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

/**
 * Babies
 */
export const GET_BABIES = 'GET_BABIES';
export const GET_BABIES_FAILED = 'GET_BABIES_FAILED';

/**
 * Activities
 */
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITY_BY_ID = 'GET_ACTIVITY_BY_ID';
export const GET_ACTIVITY_SUMMARY_BY_DATE = 'GET_ACTIVITY_SUMMARY_BY_DATE';
export const GET_ACTIVITY_TREND_BY_NAME = 'GET_ACTIVITY_TREND_BY_NAME';
export const RESET_CURRENT_ACTIVITY = 'RESET_CURRENT_ACTIVITY';
export const START_ACTIVITY = 'START_ACTIVITY';
export const UPDATE_ACTIVITY_IN_PROGRESS = 'UPDATE_ACTIVITY_IN_PROGRESS';
export const UPDATE_ACTIVITIES_IN_PROGRESS = 'UPDATE_ACTIVITIES_IN_PROGRESS';
export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';